### ISSUE TITLE
Problem mysqlconnector on command

### ISSUE THREAD

**Issue by MaximeMohandi** [MaximeMohandi/MSQBitsReporter2.0#11]
Ignoring exception in command getnews:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 17, in display_x_news
    for message in news_message.getArticlesByNewspaper():
  File "/app/msqbitsReporter/behavior/news_message.py", line 8, in getArticlesByNewspaper
    allNewspaper = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: MySQL Connection not available.
Ignoring exception in command getnews:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 17, in display_x_news
    for message in news_message.getArticlesByNewspaper():
  File "/app/msqbitsReporter/behavior/news_message.py", line 8, in getArticlesByNewspaper
    allNewspaper = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: MySQL Connection not available.
Ignoring exception in command getnews:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 17, in display_x_news
    for message in news_message.getArticlesByNewspaper():
  File "/app/msqbitsReporter/behavior/news_message.py", line 8, in getArticlesByNewspaper
    allNewspaper = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: MySQL Connection not available.
Ignoring exception in command getnews:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 17, in display_x_news
    for message in news_message.getArticlesByNewspaper():
  File "/app/msqbitsReporter/behavior/news_message.py", line 8, in getArticlesByNewspaper
    allNewspaper = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: MySQL Connection not available.
Ignoring exception in command getnewspapers:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 25, in display_list_newspapers
    for message in news_message.getAllNewspapersSaved():
  File "/app/msqbitsReporter/behavior/news_message.py", line 29, in getAllNewspapersSaved
    allNewpapers = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OperationalError: MySQL Connection not available.
Ignoring exception in command getnews:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/msqbitsReporter/discordAPI/commands_reporter.py", line 17, in display_x_news
    for message in news_message.getArticlesByNewspaper():
  File "/app/msqbitsReporter/behavior/news_message.py", line 8, in getArticlesByNewspaper
    allNewspaper = db.getJournalAll()
  File "/app/msqbitsReporter/common/Database.py", line 80, in getJournalAll
    cursor = self.cnx.cursor()
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection.py", line 809, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

**Comment by MaximeMohandi** [comment]
it's seems to be due to a timeout, after restarting docker it worked
